name: Images

on:
  push:
    branches:
      - "main"
      - "images-ci"
    paths:
      - ".github/workflows/images.yml"
      - "images/**"

jobs:
  build-mods:
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: images/restore
            file: images/restore/Dockerfile
            endpoint: demeter-run/cardano-dbsync-restore

    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          platforms: linux/amd64
          push: true
          cache-from: type=inline
          cache-to: type=inline
          tags: ghcr.io/${{ matrix.endpoint }},ghcr.io/${{ matrix.endpoint }}:${{ github.sha }}
